### ISSUE TITLE
Tesseract package incorrect arch

### ISSUE THREAD

**Issue by MrLightningBlaze** [IlNonoP/LibreRecall#1]
On the arch repositories, tesseract is just `tesseract` and not `tesseract-ocr` as the script seems to try to install. Should be a simple fix

**Comment by Samuobe** [comment]
Ops... Thank you for pointing it out

**Comment by Samuobe** [comment]
This bug was fixed whit the [V_4.0](https://github.com/IlNonoP/LibreRecall/releases/tag/V_0.4)
